// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentService.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CitizenDocumentDownloadResponse
    {
        /// <summary>
        /// Initializes a new instance of the CitizenDocumentDownloadResponse
        /// class.
        /// </summary>
        public CitizenDocumentDownloadResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CitizenDocumentDownloadResponse
        /// class.
        /// </summary>
        /// <param name="citizenDocumentFileId">The unique identifier of the
        /// Citizen Document</param>
        /// <param name="citizenDocumentFileUri">The location of the Citizen
        /// Document</param>
        public CitizenDocumentDownloadResponse(System.Guid? citizenDocumentFileId = default(System.Guid?), string citizenDocumentFileUri = default(string))
        {
            CitizenDocumentFileId = citizenDocumentFileId;
            CitizenDocumentFileUri = citizenDocumentFileUri;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the unique identifier of the Citizen Document
        /// </summary>
        [JsonProperty(PropertyName = "citizenDocumentFileId")]
        public System.Guid? CitizenDocumentFileId { get; set; }

        /// <summary>
        /// Gets or sets the location of the Citizen Document
        /// </summary>
        [JsonProperty(PropertyName = "citizenDocumentFileUri")]
        public string CitizenDocumentFileUri { get; set; }

    }
}