// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentService.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CitizenDocumentFileAccessPageData
    {
        /// <summary>
        /// Initializes a new instance of the CitizenDocumentFileAccessPageData
        /// class.
        /// </summary>
        public CitizenDocumentFileAccessPageData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CitizenDocumentFileAccessPageData
        /// class.
        /// </summary>
        public CitizenDocumentFileAccessPageData(string fileName = default(string), int? retentionPeriodInDays = default(int?), string systemName = default(string), System.DateTime? documentUploadedTime = default(System.DateTime?), string appTitle = default(string), string pageHeader = default(string), string footer = default(string))
        {
            FileName = fileName;
            RetentionPeriodInDays = retentionPeriodInDays;
            SystemName = systemName;
            DocumentUploadedTime = documentUploadedTime;
            AppTitle = appTitle;
            PageHeader = pageHeader;
            Footer = footer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "retentionPeriodInDays")]
        public int? RetentionPeriodInDays { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemName")]
        public string SystemName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentUploadedTime")]
        public System.DateTime? DocumentUploadedTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appTitle")]
        public string AppTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pageHeader")]
        public string PageHeader { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "footer")]
        public string Footer { get; set; }

    }
}
