// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentService.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CitizenDocumentUploadResponse
    {
        /// <summary>
        /// Initializes a new instance of the CitizenDocumentUploadResponse
        /// class.
        /// </summary>
        public CitizenDocumentUploadResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CitizenDocumentUploadResponse
        /// class.
        /// </summary>
        /// <param name="documentType">Possible values include:
        /// 'CitizenDocument', 'DigitalPostCoverLetter',
        /// 'SnailMailCoverLetter'</param>
        public CitizenDocumentUploadResponse(System.Guid? documentId = default(System.Guid?), string documentType = default(string), string fileAccessPageUrl = default(string))
        {
            DocumentId = documentId;
            DocumentType = documentType;
            FileAccessPageUrl = fileAccessPageUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentId")]
        public System.Guid? DocumentId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'CitizenDocument',
        /// 'DigitalPostCoverLetter', 'SnailMailCoverLetter'
        /// </summary>
        [JsonProperty(PropertyName = "documentType")]
        public string DocumentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileAccessPageUrl")]
        public string FileAccessPageUrl { get; set; }

    }
}
