// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DocumentService.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DocumentDownloadResponse
    {
        /// <summary>
        /// Initializes a new instance of the DocumentDownloadResponse class.
        /// </summary>
        public DocumentDownloadResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DocumentDownloadResponse class.
        /// </summary>
        /// <param name="documentFileId">The unique identifier of the
        /// Document</param>
        /// <param name="documentFileUri">The location of the Document</param>
        public DocumentDownloadResponse(System.Guid? documentFileId = default(System.Guid?), string documentFileUri = default(string))
        {
            DocumentFileId = documentFileId;
            DocumentFileUri = documentFileUri;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the unique identifier of the Document
        /// </summary>
        [JsonProperty(PropertyName = "documentFileId")]
        public System.Guid? DocumentFileId { get; set; }

        /// <summary>
        /// Gets or sets the location of the Document
        /// </summary>
        [JsonProperty(PropertyName = "documentFileUri")]
        public string DocumentFileUri { get; set; }

    }
}
